# Generated by Django 2.0.2 on 2018-02-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180218_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='main/static/images/avatars/default.png', upload_to='main/static/images/avatars/'),
        ),
    ]
