# Generated by Django 2.0.2 on 2018-04-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180225_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tm_sesison',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
