# Generated by Django 2.0.3 on 2018-05-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_tm_sesison'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vk_login',
            field=models.CharField(default=79776085882, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='vk_password',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='tm_sesison',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
