# Generated by Django 2.0.3 on 2018-05-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180509_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tm_sesison',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
