# Generated by Django 2.0.3 on 2018-05-25 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180513_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vk_login',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vk_password',
        ),
    ]
