# Generated by Django 2.0.3 on 2018-05-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180525_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bot_token',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
